/*
 * Copyright 2015 Panagiotis Eustratiadis
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gr.peustr.openhawking.gui;

import gr.peustr.openhawking.core.guicomponents.ActionPanel;
import com.gtranslate.Audio;
import com.gtranslate.Language;
import gr.peustr.openhawking.core.guicomponents.ResourceFrame;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import javazoom.jl.decoder.JavaLayerException;
import org.jnativehook.keyboard.NativeKeyListener;
import org.jnativehook.mouse.NativeMouseEvent;
import org.jnativehook.mouse.NativeMouseInputListener;
import org.jnativehook.mouse.NativeMouseListener;

/**
 * An application-specific implementation of the ResourceFrame abstraction.
 *
 * @author peustr
 */
public class Menu extends ResourceFrame {

    private Audio audio;
    private List<ActionPanel> actionPanels;

    /**
     * Creates new form MenuScreen
     */
    public Menu() {
        super();
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputText = new javax.swing.JTextField();
        contentPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenHawking");
        setBackground(new java.awt.Color(255, 255, 255));

        inputText.setFont(inputText.getFont().deriveFont(inputText.getFont().getStyle() & ~java.awt.Font.BOLD, 30));

        contentPane.setBackground(new java.awt.Color(255, 255, 255));
        contentPane.setLayout(new java.awt.GridLayout(3, 4));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(inputText))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() {
        audio = Audio.getInstance();
        actionPanels = new ArrayList<>();
        SimpleActionPanel p1 = new SimpleActionPanel(this, "Α - Ζ", new String[]{"α", "β", "γ", "δ", "ε", "ζ"}) {

            @Override
            public void act() {
                GUIDefaultSwitchingPolicy.getInstance().apply(getActionButtons());
            }
        };
        SimpleActionPanel p2 = new SimpleActionPanel(this, "Η - Μ", new String[]{"η", "θ", "ι", "κ", "λ", "μ"}) {

            @Override
            public void act() {
                GUIDefaultSwitchingPolicy.getInstance().apply(getActionButtons());
            }
        };
        SimpleActionPanel p3 = new SimpleActionPanel(this, "Ν - Σ", new String[]{"ν", "ξ", "ο", "π", "ρ", "σ"}) {

            @Override
            public void act() {
                GUIDefaultSwitchingPolicy.getInstance().apply(getActionButtons());
            }
        };
        SimpleActionPanel p4 = new SimpleActionPanel(this, "Τ - Ω", new String[]{"τ", "υ", "φ", "χ", "ψ", "ω"}) {

            @Override
            public void act() {
                GUIDefaultSwitchingPolicy.getInstance().apply(getActionButtons());
            }
        };
        SimpleActionPanel p5 = new SimpleActionPanel(this, "ΝΑΙ", new String[]{"ΝΑΙ"}) {

            @Override
            public void act() {
                InputStream sound = null;
                try {
                    sound = audio.getAudio("ναι", Language.GREEK);
                } catch (IOException ex) {
                    ex.printStackTrace(System.err);
                }
                try {
                    audio.play(sound);
                } catch (JavaLayerException ex) {
                    ex.printStackTrace(System.err);
                }
            }

        };
        SimpleActionPanel p6 = new SimpleActionPanel(this, "ΟΧΙ", new String[]{"ΟΧΙ"}) {

            @Override
            public void act() {
                InputStream sound = null;
                try {
                    sound = audio.getAudio("όχι", Language.GREEK);
                } catch (IOException ex) {
                    ex.printStackTrace(System.err);
                }
                try {
                    audio.play(sound);
                } catch (JavaLayerException ex) {
                    ex.printStackTrace(System.err);
                }
            }

        };
        SimpleActionPanel p7 = new SimpleActionPanel(this, "ΚΕΝΟ", new String[]{"ΚΕΝΟ"}) {

            @Override
            public void act() {
                inputText.setText(inputText.getText() + " ");
            }

        };
        SimpleActionPanel p8 = new SimpleActionPanel(this, "ΚΑΘΑΡΙΣΜΑ", new String[]{"ΚΑΘΑΡΙΣΜΑ"}) {

            @Override
            public void act() {
                inputText.setText("");
            }

        };
        SimpleActionPanel p9 = new SimpleActionPanel(this, "ΦΩΝΗ", new String[]{"ΦΩΝΗ"}) {

            @Override
            public void act() {
                InputStream sound = null;
                try {
                    sound = audio.getAudio(inputText.getText(), Language.GREEK);
                } catch (IOException ex) {
                    ex.printStackTrace(System.err);
                }
                try {
                    audio.play(sound);
                } catch (JavaLayerException ex) {
                    ex.printStackTrace(System.err);
                }
            }

        };
        contentPane.add(p1);
        contentPane.add(p2);
        contentPane.add(p3);
        contentPane.add(p4);
        contentPane.add(p5);
        contentPane.add(p6);
        contentPane.add(p7);
        contentPane.add(p8);
        contentPane.add(p9);
        actionPanels.add(p1);
        actionPanels.add(p2);
        actionPanels.add(p3);
        actionPanels.add(p4);
        actionPanels.add(p5);
        actionPanels.add(p6);
        actionPanels.add(p7);
        actionPanels.add(p8);
        actionPanels.add(p9);
        GUIDefaultSwitchingPolicy.getInstance().apply(actionPanels);
        pack();
    }

    @Override
    public List<ActionPanel> getActionPanels() {
        return actionPanels;
    }

    @Override
    public String getTextResource() {
        return inputText.getText();
    }

    @Override
    public void setTextResource(String resource) {
        inputText.setText(resource);
    }

    @Override
    protected NativeMouseListener getNativeMouseListener() {
        return new NativeMouseInputListener() {

            private static final long MILLI_THRESHOLD = 1000l;

            private long clickTimer = 0l;

            @Override
            public void nativeMouseClicked(NativeMouseEvent nme) {
            }

            @Override
            public void nativeMousePressed(NativeMouseEvent nme) {
                clickTimer = System.currentTimeMillis();
            }

            @Override
            public void nativeMouseReleased(NativeMouseEvent nme) {
                // Long time press
                if (System.currentTimeMillis() - clickTimer > MILLI_THRESHOLD) {
                    // Left click
                    if (nme.getButton() == NativeMouseEvent.BUTTON1) {
                        if (getTextResource().length() > 0) {
                            setTextResource(getTextResource().substring(0, getTextResource().length() - 1));
                        }
                    } // Right click 
                    else if (nme.getButton() == NativeMouseEvent.BUTTON2) {
                        GUIDefaultSwitchingPolicy.getInstance().apply(actionPanels);
                    }
                } // Short time press
                else {
                    //Left click
                    if (nme.getButton() == NativeMouseEvent.BUTTON1) {
                        GUIDefaultSwitchingPolicy.getInstance().select();
                    } // Right click
                    else if (nme.getButton() == NativeMouseEvent.BUTTON2) {
                        GUIDefaultSwitchingPolicy.getInstance().next();
                    }
                }
                resetTimer();
            }

            @Override
            public void nativeMouseMoved(NativeMouseEvent nme) {
            }

            @Override
            public void nativeMouseDragged(NativeMouseEvent nme) {
            }

            private void resetTimer() {
                clickTimer = 0;
            }

        };
    }

    @Override
    protected NativeKeyListener getNativeKeyListener() {
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPane;
    private javax.swing.JTextField inputText;
    // End of variables declaration//GEN-END:variables

}
