/*
 Copyright (C) 2015 Panagiotis Eustratiadis
 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 3 of the License, or
 (at your option) any later version.
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see http://www.gnu.org/licenses/.
 */
package gr.peustr.openhawking.gui;

import gr.peustr.openhawking.core.DefaultSwitchingPolicy;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author peustr
 */
public abstract class SimpleActionPanel extends ActionPanel {

    private MenuScreen parent;

    private String labelText;
    private String[] buttonTexts;

    private List<ActionButton> buttons;

    /**
     * Creates new form ButtonActionPanel
     *
     * @param parent
     * @param labelText
     * @param buttonTexts
     */
    public SimpleActionPanel(MenuScreen parent, String labelText, String[] buttonTexts) {
        this.parent = parent;
        this.labelText = labelText;
        this.buttonTexts = buttonTexts;
        buttons = new ArrayList<>();
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new javax.swing.JLabel();
        contentPane = new javax.swing.JPanel();

        setBackground(java.awt.Color.white);

        textLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        textLabel.setText("jLabel1");

        contentPane.setBackground(java.awt.Color.white);
        contentPane.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() {
        textLabel.setText(labelText);
        for (String str : buttonTexts) {
            final String curText = str;
            ActionButton jb = new ActionButton(curText) {
                @Override
                public void act() {
                    parent.getInputText().setText(parent.getInputText().getText() + curText);
                    DefaultSwitchingPolicy.getInstance().apply(parent.getActionPanels());
                }

            };
            jb.setBackgroundColor(Color.white);
            jb.setFont(jb.getFont().deriveFont(jb.getFont().getStyle() & ~java.awt.Font.BOLD, 30));
            buttons.add(jb);
            contentPane.add(jb);
        }
    }

    public List<ActionButton> getActionButtons() {
        return buttons;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
